### ISSUE TITLE
Check for `DDOS-GUARD` should be case insensitive 

### ISSUE THREAD

**Issue by mynameisbogdan** [FlareSolverr/FlareSolverrSharp#15]
anidex.info returns `<title>DDoS-Guard</title>`.

https://github.com/FlareSolverr/FlareSolverrSharp/blob/97b5d64234b6023d754f5c9d084da2a8f21a4fad/src/FlareSolverrSharp/ChallengeDetector.cs#L43

**Comment by ngosang** [comment]
https://www.nuget.org/packages/FlareSolverrSharp/3.0.5
