### ISSUE TITLE
Wrong configuration - unit tests failed

### ISSUE THREAD

**Issue by subik89** [FlareSolverr/FlareSolverrSharp#18]
Hi,

I have installed FlareSolverr service using docker on my computer. 
I ran the unit tests in ClearanceHandlerTests to check if everything works fine, but the tests are failed.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/8209905/220770244-9d2831fb-0fd2-4727-b41c-6d223a7d6bd0.png">

Could you please help me to fix this issue?

**Comment by ilike2burnthing** [comment]
Why are you posting the issue here and not FlareSolverr?

**Comment by subik89** [comment]
I am writing here, because I ran the unit tests on FlareSolverrSharp solution. I don't know exactly what is the reason of this issue.

**Comment by ilike2burnthing** [comment]
There are numerous similar issues over on the FlareSolverr repo.

General guidelines to follow: the original request should be made from the same device as FlareSolverr is running on, they should share the same IP (i.e. no VPN or proxy), and IPv6 should be disabled.

If you're following all that and still having issues, I suggest trying to run FlareSolverr natively on your computer, not in Docker.

**Comment by subik89** [comment]
Thank you for your response.
I ran FlareSolverr locally on my computer and everything works fine. Thank you for your help.
