### ISSUE TITLE
How to use proxy with FlareSolverr?

### ISSUE THREAD

**Issue by Troom** [FlareSolverr/FlareSolverrSharp#19]
Hello, I use FlareSolverr on Windows 10 with FlareSolverSharp and this solution works well for my IP address.
How can I use a proxy with FlareSolverSharp?
When I use the example from the readme file, flaresolver uses my IP address instead of the ProxyURL
```
var handler = new ClearanceHandler("http://localhost:8191/")
{
    MaxTimeout = 60000,
    ProxyUrl = "http://127.0.0.1:8888" //I need to change the proxy IP to something else
};

var client = new HttpClient(handler);
var content = await client.GetStringAsync("https://uam.hitmehard.fun/HIT");
Console.WriteLine(content);
```

**Comment by ngosang** [comment]
You are using FlareSolverrSharp correctly but the Proxy feature was implemented in the latest version:
https://github.com/FlareSolverr/FlareSolverr/releases/tag/v3.2.0

**Comment by Troom** [comment]
How should this proxy work? I just tried to use FlareSolverr running from docker and assigned my ProxyURL there. My proxy provider did not detect any request on its side.

I have newest version of flareSolverr 3.3.4.

I assumed that all traffic could be transported through a flaresolverr that would connect to my proxy provider and send a request to the given URL.

**Comment by ilike2burnthing** [comment]
https://github.com/FlareSolverr/FlareSolverr#commands
