### ISSUE TITLE
System.AggregateException: 'One or more errors occurred. (The cookies provided by FlareSolverr are not valid)'

### ISSUE THREAD

**Issue by JReverse** [FlareSolverr/FlareSolverrSharp#3]
System.AggregateException: 'One or more errors occurred. (The cookies provided by FlareSolverr are not valid)'

FlareSolverrException: The cookies provided by FlareSolverr are not valid

**Comment by ngosang** [comment]
Could yo provide more info? FlareSolverr version and URL at least.

**Comment by JReverse** [comment]
Lastest Docker/FlareSolverrSharp

.net 5

And url: https://niglet.ga/uam/hit

**Comment by ngosang** [comment]
In most cases this is caused because FlareSolverr and Jackett/FLareSolverrSharp are running in different machines or with different IPs. Read this issue => https://github.com/FlareSolverr/FlareSolverr/issues/44#issuecomment-748518756
